pub type Identifier = String;
pub type List<T> = Vec<T>;
pub type KillChainPhase = String; // TODO
pub type OpenVocab = String; // TODO
pub type Timestamp = String; // TODO
pub type Boolean = bool;
pub type ExternalReference = String; // TODO
pub type GranularMarking = String; // TODO
pub type Integer = i64;
pub type Dictionary = String; // TODO
